name: tutorial	
channels:	
  - defaults	
dependencies:	
  - pip	
  - pip:	
    - numpy==1.19.4
    - scipy==1.5.4
    - pandas==1.1.5
    - scikit-learn==0.23.2
    - mlflow==1.12.1
    - boto3==1.16.38
